"""update user

Revision ID: 3b6af19896a7
Revises: 80281f429181
Create Date: 2023-06-20 15:53:42.600303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6af19896a7'
down_revision = '80281f429181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'gender',
                sa.String(
                    length=10),
                nullable=True))
        batch_op.add_column(
            sa.Column(
                'avatar',
                sa.String(
                    length=100),
                nullable=True))
        batch_op.add_column(
            sa.Column(
                'username',
                sa.String(
                    length=50),
                nullable=False))
        batch_op.add_column(
            sa.Column(
                'password_hash',
                sa.String(
                    length=128),
                nullable=False))
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=50),
                              nullable=False)
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=False)
        batch_op.create_index('idx_unique_username', ['username'], unique=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_unique_username')
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True)
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=50),
                              nullable=True)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')
        batch_op.drop_column('avatar')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
